import { PageIntro, ContactCTA } from "@/components/page-parts";
import { Brand } from "@/components/brand";
import { RouteLink } from "@/components/navigation";
import { Icon } from "@/components/icons";
import { business, pageMetadata } from "@/lib/site";
export const metadata = pageMetadata("About Basma Al Madina Transport", "Meet BMT, a Dubai-based water supply and tanker delivery company serving residential, commercial and construction requirements across the UAE.", "/about");
export default function About() {
  return <><PageIntro label="ABOUT BASMA AL MADINA" title="A practical approach. A dependable supply.">Professional water supply and tanker delivery, with a direct line to the people arranging it.</PageIntro>
    <section className="section"><div className="container about-story"><div className="identity-panel"><Brand /><div className="identity-rings" aria-hidden="true" /><div><span className="eyebrow light">DUBAI · UNITED ARAB EMIRATES</span><p>Water for everyday life.<br /><em>Supply for the work ahead.</em></p></div></div><div><span className="eyebrow">WHO WE ARE</span><h2>Focused on what<br />your delivery needs.</h2><p>{business.name} is a Dubai-based water supply and tanker delivery company focused on reliable, responsive service for residential, commercial and construction water requirements across the UAE.</p><p>Whether it is a swimming pool fill, a construction site supply or a bulk commercial delivery, our aim is to make water delivery simple, dependable and transparent.</p><RouteLink className="text-link" href="/services">Explore what we do<Icon name="arrow" /></RouteLink></div></div></section>
    <section className="section about-principles"><div className="container"><span className="eyebrow">WORKING WITH BMT</span><div className="principles-grid"><div><h2>Built around<br />your requirements.</h2><p>Everyday supply and larger projects deserve the same clear communication.</p></div><dl><div><dt>Flexible scheduling</dt><dd>Scheduled or on-call delivery for your water supply requirements.</dd></div><div><dt>Direct communication</dt><dd>Speak with BMT by phone, WhatsApp or email.</dd></div><div><dt>A range of applications</dt><dd>Water for homes, pools, hotels, compounds, commercial properties and construction sites.</dd></div></dl></div></div></section>
    <section className="section"><div className="container office-line"><div><span className="eyebrow">OUR BASE</span><h2>Business Bay, Dubai.</h2></div><address>{business.address}</address><RouteLink className="text-link" href="/contact">Contact BMT<Icon name="arrow" /></RouteLink></div></section><ContactCTA /></>;
}
